### ISSUE TITLE
Source code for 1.3.1 doesn't include /system/user/addons/marksmin

### ISSUE THREAD

**Issue by jrrdnx** [tjdraper/marksmin#1]
There is a /marksmin directory, but it doesn't include the /vendor directory so after install PHP warnings are shown for missing Minify classes.

Side note: the main readme lists the current version as 2.0.0 instead of 1.3.1

**Comment by tjdraper** [comment]
Hi. Sorry about not having the vendor directory in there. I install marksmin through composer in all my projects so it slipped by me. And I'm sure I intended to provide a zipped stand-alone package but never did. Since I'm not currently set up to easily test the stand-alone version right at this moment, can you test this zip package?

[marksmin-1.3.1.zip](https://github.com/tjdraper/marksmin/files/3447301/marksmin-1.3.1.zip)

I've also committed to master to remove the erroneous version from the readme. I think maybe I had thought 1.3.0 would be 2.0.0 but since there were no breaking changes I decided not to. 1.3.1 is the current version.

**Comment by jrrdnx** [comment]
That works, thank you!

**Comment by tjdraper** [comment]
Great! I've also attached the zip file to the release tag if you need to download it in the future.
